version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5433:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./.env
    ports:
      - "15432:80"
volumes:
  progresDB: